version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cache_redis
    restart: always
    ports:
      - "6379:6379"

  auth:
    image: python:3.11
    container_name: auth_service
    restart: always
    working_dir: /app
    volumes:
      - ./auth-service:/app
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: main_db
      POSTGRES_HOST: db_postgres
      REDIS_HOST: cache_redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    command: tail -f /dev/null

volumes:
  pgdata:
